### ISSUE TITLE
VALIDACIÓN TAXONÓMICA | Problemas llamado api con epíteto específico

### ISSUE THREAD

**Issue by camiplata** [SIB-Colombia/data-quality-open-refine#12]
No es claro porque el llamado del API aveces falla con variedades o subespecies: 
Bactris gasipaes var. chichagui
Es encesario hacer pruebas al respecto

**Comment by RicardoOrtizG** [comment]
Creo que ese problema se soluciona con este commit: 16795da2bf2c2d420d51944ca5374c5a6d9b26e3
Este hace un split sobre el nombre canónico que lo transforma en un arreglo y llama el [1] como resultado. En ese caso siempre traería el epíteto cuando el taxon rank es  superior a especie. Sin embargo hay que hacer seguimiento si se presenta otro error

**Comment by camiplata** [comment]
El problema persiste, subo un conjunto de datos apra que hagamos pruebas sobre los nombres científicos donde el 'split' no funcionó adecuadamente.

[V20180919.openrefine.tar.gz](https://github.com/SIB-Colombia/data-quality-open-refine/files/2406109/CARDER_DWC-_Campoalegre_V20180919.openrefine.tar.gz)

**Comment by RicardoOrtizG** [comment]
Voy a revisarlo Cami, puedes tomar el pantallazo del error, para entender que está fallando ;)

**Comment by camiplata** [comment]
Se genera el suggestedSpecificEpithet, sin embargo para esos taxa no se llena el campo

**Comment by RicardoOrtizG** [comment]
Solucionado en el commit: a47bc279ca27b7fcc12c629bc64e3e6b175dc158 (Recuperación de cambios)
