### ISSUE TITLE
VALIDACIÓN TAXONÓMICA | Falta extraer autorías del género

### ISSUE THREAD

**Issue by camiplata** [SIB-Colombia/data-quality-open-refine#13]
Actuamente la autoría sugerida no funciona adecuadamente para el género. Una opción puede ser utilizar  el taxon rank para generar los condicionales que permitan una separación adecuada.

**Comment by RicardoOrtizG** [comment]
Solucionado en el commit: a47bc279ca27b7fcc12c629bc64e3e6b175dc158
