### ISSUE TITLE
Versión no es consistente con la versión en español

### ISSUE THREAD

**Issue by RicardoOrtizG** [SIB-Colombia/data-quality-open-refine#29]
La versión en español del Script de validación con speciesMatch de GBIF tiene algunos cambios para evitar traer elementos sugeridos basados en el nombre aceptado, e incluye la autoría. Es necesario actualizar ambos scripts para que solo se diferencien en el idioma y no en sus funcionalidades.

**Comment by camiplata** [comment]
@RicardoOrtizG  a que script haces referencia?

**Comment by RicardoOrtizG** [comment]
Este issue ya se corrigió con la unificación de los dos scripts
