### ISSUE TITLE
VALIDACIÓN TAXONÓMICA |  scientific name authorship

### ISSUE THREAD

**Issue by camiplata** [SIB-Colombia/data-quality-open-refine#3]
En el script 'TaxonomicValidationAPIGBIF' si el conjunto de datos tienen el elemento scientific name authorship incluir en la validación automática y traer al inicio al lado de la autoría sugerida.

**Comment by RicardoOrtizG** [comment]
Solucionado en el commit: 16795da2bf2c2d420d51944ca5374c5a6d9b26e3

**Comment by camiplata** [comment]
El booleano no esta funcionando adecuada mente ya que al recuperar la autoria a partir de otros elementos se están incluyendo espacios inecesesarios. 
Solución: Incluir una limpieza durante la creación del elemento autoría para que los booleanos funcionen.

**Comment by camiplata** [comment]
Solucionado a47bc27

**Comment by camiplata** [comment]
@RicardoOrtizG  Re-abrí el Issue para que lo puedas validar con tus acompañamientoa así estamos seguros de que todo esta OK
