### ISSUE TITLE
VALIDACIÓN TAXONÓMICA | Incluir validación nombre vs. taxonomía

### ISSUE THREAD

**Issue by camiplata** [SIB-Colombia/data-quality-open-refine#9]
Previamente a al validación con un 'backbone taxonómico' validar automáticamente la consitencia entre el nombre científico y el genero+epíteto específico+epíteto infraespecífico.

**Comment by RicardoOrtizG** [comment]
Dices hacer una validación de 1's y 0's  para el scientificName antes de hacer el llamado al API?. Lo podemos hacer en un script diferente (otro módulo), porque la solución a eso no siempre es automática.

Además, al hacer la validación con el backbone taxonómico se pueden encontrar esas inconsistencias respecto al nombre científico y  sus 'componentes' con la validación de 1's y 0's.
